### ISSUE TITLE
ycsb: add JSON option

### ISSUE THREAD

**Issue by rjnn** [cockroachdb/loadgen#112]
YCSB, being a "NoSQL" workload, is a good candidate for stress testing CockroachDB's JSON support and making sure the performance is roughly the same for similar KV-style workloads to the SQL interface.

Since there is a single table and two queries (one read, one write), refactoring the table to use a JSON schema and refactoring the queries should not involve too much refactoring.

We should add a `-json` flag to `ycsb` (rather than just replacing the current version) so that this can be done optionally, and so that we can cross compare with the non-JSON variant.

**Comment by justinj** [comment]
Fixed in #113
