### ISSUE TITLE
tpcc: fix lookup join usage

### ISSUE THREAD

**Issue by rjnn** [cockroachdb/loadgen#140]
Extracted from [this post-merge comment](https://github.com/cockroachdb/loadgen/pull/128#discussion_r170981433)

**Comment by petermattis** [comment]
This has already been done. See https://github.com/cockroachdb/loadgen/pull/132/commits/9727fcf1a39cf2031427ccbc50ac7cb6d6253baa

**Comment by rjnn** [comment]
Welp, I missed that.
