### ISSUE TITLE
make build failed

### ISSUE THREAD

**Issue by xxks-kkk** [cockroachdb/loadgen#177]
Hi,

I don't think the `make build` command is working out-of-box:

```
$ make build
GOBIN=/home/zeyuanhu/loadgen/bin go install -v \
        ./vendor/github.com/golang/lint/golint \
        ./vendor/github.com/kisielk/errcheck \
        ./vendor/golang.org/x/tools/cmd/goimports
vendor/github.com/golang/lint/golint/golint.go:19:2: cannot find package "github.com/golang/lint" in any of:
        /usr/lib/go-1.10/src/github.com/golang/lint (from $GOROOT)
        /home/zeyuanhu/go/src/github.com/golang/lint (from $GOPATH)
vendor/github.com/kisielk/errcheck/main.go:13:2: cannot find package "github.com/kisielk/errcheck/internal/errcheck" in any of:
        /usr/lib/go-1.10/src/github.com/kisielk/errcheck/internal/errcheck (from $GOROOT)
        /home/zeyuanhu/go/src/github.com/kisielk/errcheck/internal/errcheck (from $GOPATH)
vendor/github.com/kisielk/errcheck/main.go:14:2: cannot find package "github.com/kisielk/gotool" in any of:
        /usr/lib/go-1.10/src/github.com/kisielk/gotool (from $GOROOT)
        /home/zeyuanhu/go/src/github.com/kisielk/gotool (from $GOPATH)
vendor/golang.org/x/tools/cmd/goimports/goimports.go:24:2: cannot find package "golang.org/x/tools/imports" in any of:
        /usr/lib/go-1.10/src/golang.org/x/tools/imports (from $GOROOT)
        /home/zeyuanhu/go/src/golang.org/x/tools/imports (from $GOPATH)
Makefile:40: recipe for target 'deps' failed
make: *** [deps] Error 1
```
Is there any further step I need to do? I'm new to Go.

Thanks for the help!

**Comment by xxks-kkk** [comment]
I figure out the steps before doing `make build`

1. `go get -v github.com/golang/lint`
2. `go get -v github.com/kisielk/errcheck/internal/errcheck`
3. `go get -v github.com/kisielk/gotool`
4. Put "loadgen" aside with your cockroachdb source code like the following:

```
$ ls ~/go/src/github.com/cockroachdb
cockroach  loadgen
```

This is strange for me because for cockroachdb, I can directly do `make build` no matter which location I put cockroachdb source.

**Comment by rjnn** [comment]
Hi @xxks-kkk, one reason this the steps are a little broken is that we've merged the codebase into the main `cockroach` repository, in a new tool named `workload`. You can run `make bin/workload` in the cockroach repository to make the load generator tool. It also has better tooling for creating and inserting bulk data, which is necessary for some of the load generators.

We're planning to deprecate this repository and post a clear warning, sorry you caught us in the middle of this move.

**Comment by xxks-kkk** [comment]
Hi @arjunravinarayan Thanks for the info. However, I cannot find `workload` in the main `cockroach` repository. Can you help point me a link to the tool? 

Thanks!

**Comment by rjnn** [comment]
If you run `make bin/workload` in the main repository, you'll see it built in the `bin/` directory.

**Comment by arruw** [comment]
@arjunravinarayan Hey I can not find build in `bin/` directory. I'm building with docker build script, like this:

```
~/go/src/github.com/cockroachdb/cockroach$ ./build/builder.sh make bin/workload
GOPATH set to /go
Running make with -j4
github.com/cockroachdb/cockroach/vendor/github.com/tylertreat/hdrhistogram-writer
github.com/cockroachdb/cockroach/pkg/ccl/workloadccl
github.com/cockroachdb/cockroach/pkg/ccl/workloadccl/roachmartccl
github.com/cockroachdb/cockroach/pkg/workload/bank
github.com/cockroachdb/cockroach/pkg/workload/jsonload
github.com/cockroachdb/cockroach/pkg/workload/kv
github.com/cockroachdb/cockroach/pkg/workload/singlequery
github.com/cockroachdb/cockroach/pkg/workload/tpcc
github.com/cockroachdb/cockroach/pkg/workload/tpch
github.com/cockroachdb/cockroach/pkg/workload/ycsb
github.com/cockroachdb/cockroach/pkg/ccl/workloadccl/allccl
github.com/cockroachdb/cockroach/pkg/cmd/workload
```

After building my `./bin` directory is empty:
```
~/go/src/github.com/cockroachdb/cockroach$ ls -al ./bin
total 8
drwxr-xr-x  2 root      root      4096 Apr 14 10:25 .
drwxrwxr-x 18 matjazmav matjazmav 4096 Apr 14 10:33 ..
```
