### ISSUE TITLE
TPC-C output format

### ISSUE THREAD

**Issue by seybi87** [cockroachdb/loadgen#186]
Hi guys, 
is there any config option, which handles the output format of the TPC-C load generator, e.g. to get the output in a more structured way such as JSON, CSV,...

Any recommendations are much appreciated

**Comment by jordanlewis** [comment]
Unfortunately not. PRs are accepted. Please do know that development of the tpcc load generator has moved to the main repo, in `pkg/workload/tpcc`. Thanks!
