### ISSUE TITLE
Error while running tpcc workload against 3-node cluster

### ISSUE THREAD

**Issue by seybi87** [cockroachdb/loadgen#188]
Hi guys,

I am trying to run the TPC-C workload against a 3-node cluster. Hereby, I basically follow this [article](https://www.cockroachlabs.com/docs/stable/performance-benchmarking-with-tpc-c.html#step-4-run-the-benchmark). Yet, I am facing the following error:
`Error: failed insert into district: pq: relation "district" does not exist`

I have checked the dashboard and all tables are created but no data is inserted:

![image](https://user-images.githubusercontent.com/6516819/46087437-9ef11180-c1aa-11e8-8bc1-bb44a5df0ec0.png)

Here are some more technical details:

CockroachDB version: 2.0.3
Loadgen: latest version from https://edge-binaries.cockroachdb.com/cockroach/workload.LATEST

Command: 
`./loadgen.sh run tpcc  --drop --init --ramp=30s  --duration=300s   --warehouses=10 --scatter --split "postgres://192.168.100.5:26257?sslmode=disable postgres://192.168.100.12:26257?sslmode=disable postgres://192.168.100.38:26257?sslmode=disable"`

Yet, when running the workload only with one node in the connection URL it works without issues but the load is mainly issued against the provided node and not balanced across the cluster.

Command:
`./loadgen.sh run tpcc  --drop --init --ramp=30s  --duration=300s   --warehouses=10 --scatter --split "postgres://192.168.100.5:26257?sslmode=disable"`

Thanks in advance for any help

**Comment by nvb** [comment]
Hi @seybi87, thanks for the interesting CockroachDB and thanks for the detailed report of what you're seeing. From it, I think I have a pretty good idea of what's going wrong.

Schema changes in CockroachDB are gossiped, which means that it's possible for one SQL gateway (a Cockroach node serving SQL traffic) to know about a schema change before others. For all intents and purposes, this is fine and will it will never cause any consistency violations, but it does introduce a race that I think we're seeing here. It's possible for a node to perform a schema change (`create table district`) and return to the client before other nodes are aware of this schema change. If the client then goes and talks to another node, it may win the race against gossip and be confused when the other node doesn't know about the schema change it just performed.

This comes up very rarely in practice, so I wonder if your cluster has large network delays or something. Regardless, we can get around this pretty easily by just breaking up the steps of initializing the schema and then running the load. Could you try the following two commands and let me know if you run into the same issue?

```
./loadgen.sh init tpcc --drop --warehouses=10 --scatter --split "postgres://192.168.100.5:26257?sslmode=disable"
./loadgen.sh run tpcc --ramp=30s --duration=300s --warehouses=10 "postgres://192.168.100.5:26257?sslmode=disable postgres://192.168.100.12:26257?sslmode=disable postgres://192.168.100.38:26257?sslmode=disable"
```

**Comment by seybi87** [comment]
Hi @nvanbenschoten , 
thanks a lot for the detailed explanation about the internal steps  which are ongoing to ensure consistency.

With respect to the potential network delays, I can share some details about our setup:
All CockroachDB nodes and the Loadgen client are hosted on separate VMs in a private OpenStack and communicating over a private network (10G). Hence, network delays are quite unlikely but I can also perform a detailed analysis with iperf if required.   

With respect to your suggested commands:
The following command worked as expected:
`./loadgen.sh init tpcc --drop --warehouses=10 --scatter --split "postgres://192.168.100.5:26257?sslmode=disable"`
But the actual workload execution failed:
` ./loadgen.sh run tpcc --ramp=30s --duration=300s --warehouses=10 "postgres://192.168.100.5:26257?sslmode=disable postgres://192.168.100.12:26257?sslmode=disable postgres://192.168.100.38:26257?sslmode=disable"
Error: pq: unsupported sslmode "disable postgres://192.168.100.12:26257?sslmode=disable postgres://192.168.100.38:26257?sslmode=disable"; only "require" (default), "verify-full", "verify-ca", and "disable" supported`

It seems that there is an issue with parsing the connection URL?

Thanks for any further advices

**Comment by nvb** [comment]
Thanks @seybi87. Could you try wrapping each connection URL in its own set of quotes instead of putting them all together? Something like:

```
./loadgen.sh run tpcc --ramp=30s --duration=300s --warehouses=10 "postgres://192.168.100.5:26257?sslmode=disable" "postgres://192.168.100.12:26257?sslmode=disable" "postgres://192.168.100.38:26257?sslmode=disable"
```

**Comment by seybi87** [comment]
Hi @nvanbenschoten , 
thanks again for your support. 

Your proposed solution solved the problem 👍 

In addition,  wrapping each connection URL in its own set of quotes also solves the issue 
`Error: failed insert into district: pq: relation "district" does not exist` 
when I combine the init and run phase in one command as stated in my initial request. 


Finally the full command:
`./loadgen.sh run tpcc --drop --init --ramp=30s --duration=300s --warehouses=10 --scatter --split "postgres://192.168.100.5:26257?sslmode=disable" "postgres://192.168.100.12:26257?sslmode=disable" "postgres://192.168.100.38:26257?sslmode=disable"`

Thanks again for your support.
