### ISSUE TITLE
Add a %-utilization control to kv load-generator

### ISSUE THREAD

**Issue by spencerkimball** [cockroachdb/loadgen#32]
Two possible mechanisms which come to mind are:
- A manual pause time between successive operations
- Run at full tilt for 30s to measure maximum throughput, and then add pauses to bring throughput to `x%` of the maximum.

**Comment by petermattis** [comment]
I'd prefer specifying a rate-limit of ops/sec on the command line and implement that either using a fixed delay between ops or a [token bucket](https://godoc.org/golang.org/x/time/rate). Trying to do something fancier where we measure the maximum throughput and then adjust seems excessive. Specifying the delay between ops manually is asking the user to do math which the computer can more easily do.

**Comment by spencerkimball** [comment]
OK, that's straightforward enough.
