### ISSUE TITLE
Ycsb: print more output during initial load phase 

### ISSUE THREAD

**Issue by rjnn** [cockroachdb/loadgen#54]

**Comment by petermattis** [comment]
Alternately, we could make the initial load phase use the normal workers but only perform writes, similar to the way `--write-duration` switches the workers to only performing reads. This would be relatively straightforward, would speed up the initial load phase and would reuse the existing periodic output.

**Comment by petermattis** [comment]
@arjunravinarayan I'm going to implement my suggestion unless you see a reason not to.

**Comment by rjnn** [comment]
Go for it. Sorry for the late reply, this skipped my email filters for some reason.
