### ISSUE TITLE
tpcc: add txn retries

### ISSUE THREAD

**Issue by rjnn** [cockroachdb/loadgen#75]
Now that TPC-C forces serializability, leveling the playing field between CockroachDB and Postgres, Postgres gives up on some transactions with a "deadlock detected".

We need to add retry logic when these deadlocks occur, so that the load generator does not fail.

**Comment by rjnn** [comment]
After discussion with @jordanlewis we think this would be unfair to Postgres. Instead we should have a "postgres mode" where we run a subset of queries with `SELECT FOR UPDATE` (this has to be in an explicit mode since CockroachDB does not currently accept that syntax). `SELECT FOR UPDATE` would be faster on Postgres than doing a manual retry from the load generator when the deadlock is detected.

**Comment by bdarnell** [comment]
I think we should do both for comparison: SERIALIZABLE is a safer solution since there's no opportunity to forget the FOR UPDATE clause, so it would be good to quantify that tradeoff.

**Comment by jordanlewis** [comment]
This is done now.
