### ISSUE TITLE
Info on running

### ISSUE THREAD

**Issue by dream4r1** [cockroachdb/loadgen#93]
Hello,

Thanks for the loadgen module for cockroachdb. The README is not fully compiled I believe is docker an prerequisite for this loadgen module ?. If not can you list the basic steps on how to run this against an cockroachdb cluster. Thank you.

Regards,
Ilan

**Comment by a-robinson** [comment]
```
make build PKG=kv
./kv/kv
```

Replace `kv` with your favorite load generator name as necessary. No Docker necessary. Run `./kv/kv --help` if you want to see the available options, but by default it'll connect to localhost at the default cockroach port.

**Comment by dream4r1** [comment]
Wow this one requires alot of dependency packages. But the command worked.  Thanks for the quick help.

**Comment by a-robinson** [comment]
@arjunravinarayan is also documenting it for the future - https://github.com/cockroachdb/loadgen/pull/94. Thanks for pointing out that it wasn't documented!
