### ISSUE TITLE
tpcc: errors.Wrapf breaks crdb.Tx

### ISSUE THREAD

**Issue by danhhz** [cockroachdb/loadgen#98]
See https://github.com/cockroachdb/cockroach-go/issues/16

crdb.Tx retries retryable errors, but the sniffing of this is broken by wrapping them. As a result, we're not retrying when we should:

```
2017/11/09 21:16:26 error in payment: select by last name fail: pq: restart transaction: HandledRetryableTxnError: TransactionAbortedError: txn aborted "sql txn" id=7f5561b8 key=/Table/51/1/98/0 rw=true pri=0.03538397 iso=SERIALIZABLE stat=ABORTED epo=1 ts=1510280185.403832112,107 orig=1510280185.403832112,107 max=1510280183.481292605,72 wto=false rop=false seq=6
```

In the short term, we should probably remove errors.Wrapf inside any crdb.Tx closures in this repo. In the long term, perhaps there's a way to add them back.

**Comment by andreimatei** [comment]
the cockroach-go lib has already started emulating parts of pkg/errors. I guess at this point we might emulate the Cause method too.

**Comment by jordanlewis** [comment]
This got fixed at some point - the library now unwraps the error properly.
